name: Lint, Check, and Build

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    check-and-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 26
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Run lint(Extension)
              run: npm run lint

            - name: Run lint(Website)
              run: npm run lint -w website

            - name: Run checks(Extension)
              run: npm run check

            - name: Run checks(Website)
              run: npm run check -w website

            - name: Build project(Extension)
              run: npm run build

            - name: Build project(Website)
              run: npm run build -w website
